spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost/formacion
    password: Postgres.
  application:
    name: servicio-cursos
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}:${spring.application.name}
server:
  port: '8081'
springdoc:
  packagesToScan: com.curso.serviciocursos.controller
  pathsToMatch: /**
